apiVersion: v1
kind: ConfigMap
metadata:
  name: git-providers-endpoints
  namespace: system
data:
  github: |
    fqdn: github.com
    authentication: https://api.github.com/user
  gitlab: |
    fqdn: gitlab.com
    authentication: https://gitlab.com/api/v4/user
  bitbucket: |
    fqdn: bitbucket.org
    authentication: https://api.bitbucket.org/2.0/user
  # custom: |
  #   fqdn: custom_fqdn
  #   authentication: custom_fqdn/api_endpoint_to_check_if_user_is_connected
