---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kgio-dams-kgio-v1-remotesyncer
  failurePolicy: Fail
  name: vremotesyncer.kb.io
  rules:
  - apiGroups:
    - kgio.dams.kgio
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - remotesyncers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kgio-dams-kgio-v1-remoteuser
  failurePolicy: Fail
  name: vremoteuser.kb.io
  rules:
  - apiGroups:
    - kgio.dams.kgio
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - remoteusers
  sideEffects: None
