---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwRENDQW95Z0F3SUJBZ0lVTEVJcXBoY2luNVFLd1B5dkdzTmhGZjJVajZjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRUxNQWtHQTFVRUJoTUNRVlV4R3pBWkJnTlZCQU1NRW5kbFltaHZiMnN0YzJWeWRtbGpaUzFEUVRBZQpGdzB5TkRBMU1qRXlNREU0TVRGYUZ3MHlOVEExTWpFeU1ERTRNVEZhTUM0eEN6QUpCZ05WQkFZVEFrRlZNUjh3CkhRWURWUVFEREJaM1pXSm9iMjlyTFhObGNuWnBZMlV0WTJ4cFpXNTBNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1YzUvWld0WlBIU2hKZUNPY1hQOW54bVl1SzRXakNuekJBZUF5aEtVRE1EdQpDdzdaRVdtYnNXdEdOZm1IZURXMC9MNDZYVURITXNjVjJNSXpwVVExTjM1UlFMODhBazFjMEp4SVNaT3VXb1h0ClM0QXhqQmVHSnMvMlBNN0NwMk9lbUZwZFA2NTYrbEZXdjZGb2Z2K3lBT2V6dGFBbkVRUGxmMCtWSGhXSmJENHcKMjNLVjRicEJzSWJxVW1pT2N4SWZzaHdVQ0l3a2NPczVKZjNhenZ4cjRocHROTWFkYzhKc0dQN0xHZTZRcnVweApXWHFLdG1pa3R6L3kvQ0RVQldVSUN6eGJ6a3Jxa1B3ZDdQb3JtcTB1NEltc2pLZGE3YnhYY3d2ZFYxSy9uaUdFCkRBM25PdXBoT2p4QXNvQ2phUE4yVFBnRkFET3hheVdzTWdIaFFIU1RnUUlEQVFBQm80RzlNSUc2TUhnR0ExVWQKRVFSeE1HK0NMRzl3WlhKaGRHOXlMWGRsWW1odmIyc3RjMlZ5ZG1salpTNXZjR1Z5WVhSdmNpMXplWE4wWlcwdQpjM1pqZ2pseVpYTnZkWEpqWlhNdGFXNTBaWEpqWlhCMGIzSXRkMlZpYUc5dmF5MXpaWEoyYVdObExtOXdaWEpoCmRHOXlMWE41YzNSbGJTNXpkbU9IQkt3UkFBRXdIUVlEVlIwT0JCWUVGT29tTStDdXl6SFhLS09DVW4yNVI0MFQKMDlUVk1COEdBMVVkSXdRWU1CYUFGSGo3Z0VJSkVQMGlwMVpCbWtKY0hTVmNrVjBFTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQlVPWGlMc2NvYytrZXlNaThVby9rRWwzTkl6UEZnd3ZRQU5PaHZDbktZZHhaU0IvdmpXdXBmClhPcDJhYWN4VVlQeTB6Rk1RaVhOanFHMzBaUmVtVzFvMXpBeExvaVNNNkFQVDlCczFSTWF6eW83TUwrY2RUVUgKMTNmcnVjSFVpS29FMkQxNTVDVW55aVFlQ2FUQzJXdGJuckhRVU14OTJuaHBJSGttZ1lvbXB2cUJYRXorcTFxRQo0TTFZdTREWGxMdWI5bE9RS05TWGxwRUp4WFZiVERmVmhYVGQyNUtYWjcwbTVKLzZEcExlTFNxS09uY3BUanlGClkreHNZMTIvc3RwUm5qT3paZVNvMm5JQVdpTlQrNnFqM3lxNWRkSW9SY0lzYzJwenBSdENDenZqd0VEdm5yU3MKU2VLRzFwVFlwYnFkb015SHplaW4xTWUwaEY1UzJ0RXgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /validate-kgio-dams-kgio-v1-gitremote
  failurePolicy: Fail
  name: vgitremote.kb.io
  rules:
  - apiGroups:
    - kgio.dams.kgio
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gitremotes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwRENDQW95Z0F3SUJBZ0lVTEVJcXBoY2luNVFLd1B5dkdzTmhGZjJVajZjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRUxNQWtHQTFVRUJoTUNRVlV4R3pBWkJnTlZCQU1NRW5kbFltaHZiMnN0YzJWeWRtbGpaUzFEUVRBZQpGdzB5TkRBMU1qRXlNREU0TVRGYUZ3MHlOVEExTWpFeU1ERTRNVEZhTUM0eEN6QUpCZ05WQkFZVEFrRlZNUjh3CkhRWURWUVFEREJaM1pXSm9iMjlyTFhObGNuWnBZMlV0WTJ4cFpXNTBNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1YzUvWld0WlBIU2hKZUNPY1hQOW54bVl1SzRXakNuekJBZUF5aEtVRE1EdQpDdzdaRVdtYnNXdEdOZm1IZURXMC9MNDZYVURITXNjVjJNSXpwVVExTjM1UlFMODhBazFjMEp4SVNaT3VXb1h0ClM0QXhqQmVHSnMvMlBNN0NwMk9lbUZwZFA2NTYrbEZXdjZGb2Z2K3lBT2V6dGFBbkVRUGxmMCtWSGhXSmJENHcKMjNLVjRicEJzSWJxVW1pT2N4SWZzaHdVQ0l3a2NPczVKZjNhenZ4cjRocHROTWFkYzhKc0dQN0xHZTZRcnVweApXWHFLdG1pa3R6L3kvQ0RVQldVSUN6eGJ6a3Jxa1B3ZDdQb3JtcTB1NEltc2pLZGE3YnhYY3d2ZFYxSy9uaUdFCkRBM25PdXBoT2p4QXNvQ2phUE4yVFBnRkFET3hheVdzTWdIaFFIU1RnUUlEQVFBQm80RzlNSUc2TUhnR0ExVWQKRVFSeE1HK0NMRzl3WlhKaGRHOXlMWGRsWW1odmIyc3RjMlZ5ZG1salpTNXZjR1Z5WVhSdmNpMXplWE4wWlcwdQpjM1pqZ2pseVpYTnZkWEpqWlhNdGFXNTBaWEpqWlhCMGIzSXRkMlZpYUc5dmF5MXpaWEoyYVdObExtOXdaWEpoCmRHOXlMWE41YzNSbGJTNXpkbU9IQkt3UkFBRXdIUVlEVlIwT0JCWUVGT29tTStDdXl6SFhLS09DVW4yNVI0MFQKMDlUVk1COEdBMVVkSXdRWU1CYUFGSGo3Z0VJSkVQMGlwMVpCbWtKY0hTVmNrVjBFTUEwR0NTcUdTSWIzRFFFQgpDd1VBQTRJQkFRQlVPWGlMc2NvYytrZXlNaThVby9rRWwzTkl6UEZnd3ZRQU5PaHZDbktZZHhaU0IvdmpXdXBmClhPcDJhYWN4VVlQeTB6Rk1RaVhOanFHMzBaUmVtVzFvMXpBeExvaVNNNkFQVDlCczFSTWF6eW83TUwrY2RUVUgKMTNmcnVjSFVpS29FMkQxNTVDVW55aVFlQ2FUQzJXdGJuckhRVU14OTJuaHBJSGttZ1lvbXB2cUJYRXorcTFxRQo0TTFZdTREWGxMdWI5bE9RS05TWGxwRUp4WFZiVERmVmhYVGQyNUtYWjcwbTVKLzZEcExlTFNxS09uY3BUanlGClkreHNZMTIvc3RwUm5qT3paZVNvMm5JQVdpTlQrNnFqM3lxNWRkSW9SY0lzYzJwenBSdENDenZqd0VEdm5yU3MKU2VLRzFwVFlwYnFkb015SHplaW4xTWUwaEY1UzJ0RXgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: webhook-service
      namespace: system
      path: /validate-kgio-dams-kgio-v1-resourcesinterceptor
  failurePolicy: Fail
  name: vresourcesinterceptor.kb.io
  rules:
  - apiGroups:
    - kgio.dams.kgio
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcesinterceptors
  sideEffects: None
