# permissions for end users to view gituserbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gituserbinding-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: gituserbinding-viewer-role
rules:
- apiGroups:
  - kgio.dams.kgio
  resources:
  - gituserbindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kgio.dams.kgio
  resources:
  - gituserbindings/status
  verbs:
  - get
