# permissions for end users to view remotesyncers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: remotesyncer-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: new-operator
    app.kubernetes.io/part-of: new-operator
    app.kubernetes.io/managed-by: kustomize
  name: remotesyncer-viewer-role
rules:
- apiGroups:
  - syngit.damsien.fr
  resources:
  - remotesyncers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - syngit.damsien.fr
  resources:
  - remotesyncers/status
  verbs:
  - get
