# permissions for end users to edit resourcesinterceptors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: resourcesinterceptor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: resourcesinterceptor-editor-role
rules:
- apiGroups:
  - kgio.dams.kgio
  resources:
  - resourcesinterceptors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgio.dams.kgio
  resources:
  - resourcesinterceptors/status
  verbs:
  - get
