---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kgio.dams.kgio
  resources:
  - gituserbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgio.dams.kgio
  resources:
  - gituserbindings/finalizers
  verbs:
  - update
- apiGroups:
  - kgio.dams.kgio
  resources:
  - gituserbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kgio.dams.kgio
  resources:
  - resourcesinterceptors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgio.dams.kgio
  resources:
  - resourcesinterceptors/finalizers
  verbs:
  - update
- apiGroups:
  - kgio.dams.kgio
  resources:
  - resourcesinterceptors/status
  verbs:
  - get
  - patch
  - update
