---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgio.dams.kgio
  resources:
  - remoteUser
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kgio.dams.kgio
  resources:
  - remoteuserbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kgio.dams.kgio
  resources:
  - remoteuserbindings/finalizers
  verbs:
  - update
- apiGroups:
  - kgio.dams.kgio
  resources:
  - remoteuserbindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - syngit.dams.syngit
  resources:
  - remotesyncers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - syngit.dams.syngit
  resources:
  - remotesyncers/finalizers
  verbs:
  - update
- apiGroups:
  - syngit.dams.syngit
  resources:
  - remotesyncers/status
  verbs:
  - get
  - patch
  - update
