---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    # service:
    #   name: webhook-service
    #   namespace: system
    #   path: /validate-kgio-dams-kgio-v1-gitremote
    url: https://172.17.0.1:9443/validate-kgio-dams-kgio-v1-gitremote
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMekNDQWhlZ0F3SUJBZ0lVUWhvUnAwNVNHdVYvNFVHV2txUk14c2xpeElZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0p6RUxNQWtHQTFVRUJoTUNRVlV4R0RBV0JnTlZCQU1NRDNkbFltaHZiMnN0YzJWeWRtbGpaVEFlRncweQpOREExTVRReE9EQTRNakZhRncweU5UQTFNVFF4T0RBNE1qRmFNQ2N4Q3pBSkJnTlZCQVlUQWtGVk1SZ3dGZ1lEClZRUUREQTkzWldKb2IyOXJMWE5sY25acFkyVXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRQzFuTU55OGNNZVhMZW9xZitHd0NIQzRaZU9ZMFlwMFVoZmRRM0M4MG1saHQwVWVsYm53R3ovWGpOSQpUZkdSdVptWUU2NkZ4VysrUmEyQXZ4V0dkMVVuSFVqRjhxcGN3KzBJVE0xUDZIWnVieldLWHFKbHNJaEVrNXBECktuMEpwRDJnZU1XNWhhcDdMdUZzUklIbkdhVDROSzVDVnhiazF1S09OWG1wdmlWR3d4Q2lCcnlobXlnKytkaXoKQzAvSWI5TkRmeTBPZlowVG9ZcnROWWpzRTNGdGV3cDh0U29kYWxBUWZjU3pjRkdSckdRUTV5SHp3SHQrell0UQpOMGFiK1BTc2JPdTh3eGRXdEkwSE41cEJ3WWpTQ29qVEtoM016MWxSUFlYbFNNcmpFNEhpNFJCanMzTXpQTFNkCldYb3o3ckxlelF6K09MVFBtOHdVeVNPV2NkcDdBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlJSRnZ0TnFtZXkKQ08zTHFrdWY4R2hNcDB5R01qQWZCZ05WSFNNRUdEQVdnQlJSRnZ0TnFtZXlDTzNMcWt1ZjhHaE1wMHlHTWpBUApCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXR5b2pkcEFSQ3lNcHdzRlRGClNWd29BNWNpYVZ2STVDK3AvWlV1ams2SkVqZm9CVFJoNW4vUUNZQ29VMFRxMElieEQyeEQ2M0ROZmtNa3cvSVAKYzdWQmp3WXBwWk5EalN4NnM5TkxBejU4dGkwMEt1am8wZ2pmRGxMc3JLaHR0OTVEYm5MeTZxMFE0TzY5OHpBKwo3RFdpSkNEVXNDOElxUCtHNDRJZXB5NURZMmJ3K3gvN0p1eG8vaURhZkdkSTNZeE9TcFk0bkdTZVlHbmRvZWIxCkJhc29PVmc0Qm5LblVvNHV1WEtTTHo5YXFuSCtQZWxSTVJrU3B3NUR4YmhyU1lOMHBWSWZvVEZjV1hHTG1EbGYKV2xOZ0tNcDRnTDJBb2FHSlllb2pCRElQUDV1YXh3ZDlrem5TcThONWdKditBTnU5WXZEcXYwaHpPakRoTEg1bgowUEJoCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  failurePolicy: Fail
  name: vgitremote.kb.io
  rules:
  - apiGroups:
    - kgio.dams.kgio
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - gitremotes
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    # service:
    #   name: webhook-service
    #   namespace: system
    #   path: /validate-kgio-dams-kgio-v1-resourcesinterceptor
    url: https://172.17.0.1:9443/validate-kgio-dams-kgio-v1-resourcesinterceptor
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURMekNDQWhlZ0F3SUJBZ0lVUWhvUnAwNVNHdVYvNFVHV2txUk14c2xpeElZd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0p6RUxNQWtHQTFVRUJoTUNRVlV4R0RBV0JnTlZCQU1NRDNkbFltaHZiMnN0YzJWeWRtbGpaVEFlRncweQpOREExTVRReE9EQTRNakZhRncweU5UQTFNVFF4T0RBNE1qRmFNQ2N4Q3pBSkJnTlZCQVlUQWtGVk1SZ3dGZ1lEClZRUUREQTkzWldKb2IyOXJMWE5sY25acFkyVXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRQzFuTU55OGNNZVhMZW9xZitHd0NIQzRaZU9ZMFlwMFVoZmRRM0M4MG1saHQwVWVsYm53R3ovWGpOSQpUZkdSdVptWUU2NkZ4VysrUmEyQXZ4V0dkMVVuSFVqRjhxcGN3KzBJVE0xUDZIWnVieldLWHFKbHNJaEVrNXBECktuMEpwRDJnZU1XNWhhcDdMdUZzUklIbkdhVDROSzVDVnhiazF1S09OWG1wdmlWR3d4Q2lCcnlobXlnKytkaXoKQzAvSWI5TkRmeTBPZlowVG9ZcnROWWpzRTNGdGV3cDh0U29kYWxBUWZjU3pjRkdSckdRUTV5SHp3SHQrell0UQpOMGFiK1BTc2JPdTh3eGRXdEkwSE41cEJ3WWpTQ29qVEtoM016MWxSUFlYbFNNcmpFNEhpNFJCanMzTXpQTFNkCldYb3o3ckxlelF6K09MVFBtOHdVeVNPV2NkcDdBZ01CQUFHalV6QlJNQjBHQTFVZERnUVdCQlJSRnZ0TnFtZXkKQ08zTHFrdWY4R2hNcDB5R01qQWZCZ05WSFNNRUdEQVdnQlJSRnZ0TnFtZXlDTzNMcWt1ZjhHaE1wMHlHTWpBUApCZ05WSFJNQkFmOEVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQXR5b2pkcEFSQ3lNcHdzRlRGClNWd29BNWNpYVZ2STVDK3AvWlV1ams2SkVqZm9CVFJoNW4vUUNZQ29VMFRxMElieEQyeEQ2M0ROZmtNa3cvSVAKYzdWQmp3WXBwWk5EalN4NnM5TkxBejU4dGkwMEt1am8wZ2pmRGxMc3JLaHR0OTVEYm5MeTZxMFE0TzY5OHpBKwo3RFdpSkNEVXNDOElxUCtHNDRJZXB5NURZMmJ3K3gvN0p1eG8vaURhZkdkSTNZeE9TcFk0bkdTZVlHbmRvZWIxCkJhc29PVmc0Qm5LblVvNHV1WEtTTHo5YXFuSCtQZWxSTVJrU3B3NUR4YmhyU1lOMHBWSWZvVEZjV1hHTG1EbGYKV2xOZ0tNcDRnTDJBb2FHSlllb2pCRElQUDV1YXh3ZDlrem5TcThONWdKditBTnU5WXZEcXYwaHpPakRoTEg1bgowUEJoCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  failurePolicy: Fail
  name: vresourcesinterceptor.kb.io
  rules:
  - apiGroups:
    - kgio.dams.kgio
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcesinterceptors
  sideEffects: None
